# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16ae2b8fb5404a14cee6d64173c1495eafa38e963c4d451b927fb8b7ee6d6d9eb2be63ffbfe0301b841d67c10cef81eb729f98a40946e5865db43444c1edc6eb

test:
  secret_key_base: c912abf660aa10d73884d6c79cb5ed3928a8dfa5ee9ba4274db832377e9285b195eb053bb64172bbd87746a0ca4d3cb802762a1343e8d57fbf753262d13b6421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
